const data = [
    {
      id: 1,
      title: 'Vegetable Biryani',
      category: 'Nandini Restaurant',
      price: 100.00,
      img: './images/Veg_Biryani.jpg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
      quantity: 0,
    },
    {
      id: 2,
      title: 'Bisibele Bath',
      category: 'Nagarjuna Restaurant',
      price: 50.00,
      img: './images/Bisibelebath.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
      quantity: 2,
    },
    {
      id: 3,
      title: 'Chicken Biryani',
      category: 'Anand Restaurant',
      price: 180.00,
      img: './images/Chicken_Biryani.jpg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
      quantity: 0,
    },
    {
      id: 4,
      title: 'Idli & Vada',
      category: 'Nandini Restaurant',
      price: 40.00,
      img: './images/Idli_vada.jpg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
      quantity: 0,
    },
    {
      id: 5,
      title: 'Chow Chow Path',
      category: 'Nagarjuna Restaurant',
      price: 65.00,
      img: './images/Chowchowpath.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
      quantity: 0,
    },
    {
      id: 6,
      title: 'Poori',
      category: 'Anand Restaurant',
      price: 70.00,
      img: './images/Poori.jpg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
      quantity: 0
    },
    {
      id: 7,
      title: 'Masala Dosa',
      category: 'Nandini Restaurant',
      price: 60.00,
      img: './images/Masala_dosa.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
      quantity: 0,
    },
    {
      id: 8,
      title: 'South Indina Thali',
      category: 'Nagarjuna Restaurant',
      price: 180.00,
      img: './images/SouthIndia_Thali.jpg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
      quantity: 1,
    },
    {
      id: 9,
      title: 'North Indina Thali',
      category: 'Anand Restaurant',
      price: 200.00,
      img: './images/NorthIndian_Thali.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
      quantity: 0,
    },
  ];
  export default data;
  